/* Dependency-free fictional calendar-benefit demo. */
const STORAGE_KEY = "calenfit-calendar-benefit-v1";
const SCHEMA_VERSION = 1;
const today = new Date("2026-09-01T09:00:00+09:00");
const MAX_EVIDENCE_BYTES = 10 * 1024 * 1024;
const PROFILE = Object.freeze({ age: 25, birthYear: 2001, residence: "경기도 하남시", status: "미취업", education: "대학교 4학년", goal: "취업 준비", isDemo: true });
const POLICY_IDS = Object.freeze(["interview-allowance", "exam-support", "hanam-basic-income", "youth-hope-savings", "future-tomorrow-experience"]);
const POLICY_STATES = Object.freeze(["open", "closed", "exhausted", "unknown"]);
const SEED_POLICIES = [
  { id:"interview-allowance", title:"경기도 청년 면접수당", category:"면접", amount:"1회 5만원 (연 최대 15만원)", organization:"경기도 · 잡아바", status:"open", checkedAt:"2026-09-01 08:30", sourceUrl:"https://www.gg.go.kr/contents/contents.do?ciIdx=987029&menuId=265937", applicationUrl:"https://apply.jobaba.net/", officialUrl:"https://apply.jobaba.net/", conditionSummary:"경기도 거주, 미취업 청년, 면접 참여 증빙 필요", requirements:["경기도 거주","미취업 상태","면접 참여 사실","신청 기한 내 접수"], evidence:["면접확인서","채용공고","면접 안내문","결과 안내","현장 사진 또는 명함"], isDemo:true },
  { id:"exam-support", title:"경기청년 역량강화 기회지원", category:"시험", amount:"최대 30만원", organization:"경기도", status:"unknown", checkedAt:"2026-09-01 08:45", sourceUrl:"https://web1.gg.go.kr/contents/contents.do?ciIdx=987323&menuId=1534171", applicationUrl:"https://apply.jobaba.net/", officialUrl:"https://apply.jobaba.net/", conditionSummary:"경기도 청년 대상 어학·자격시험 응시료 지원", requirements:["경기도 거주","응시 사실","영수증 보관","지원 대상 시험인지 확인"], evidence:["응시 확인서","결제 영수증","성적표 또는 접수 내역"], isDemo:true },
  { id:"hanam-basic-income", title:"하남시 청년기본소득", category:"생활지원", amount:"분기별 25만원 · 연 최대 100만원", organization:"하남시 · 경기도", status:"unknown", checkedAt:"2026-09-02 09:00", sourceUrl:"https://www.hanam.go.kr/www/contents.do?key=12491", applicationUrl:"https://apply.jobaba.net/special/gibon/main.do", officialUrl:"https://apply.jobaba.net/special/gibon/main.do", conditionSummary:"하남시 거주 만 24세 청년, 경기도 3년 연속 또는 합산 10년 거주 조건 확인", requirements:["하남시 주민등록","만 24세 해당 출생일 구간","경기도 3년 연속 또는 합산 10년 거주","주민등록초본 확인"], evidence:["주민등록초본","기초생활수급자 증명서(해당 시)"], isDemo:true },
  { id:"youth-hope-savings", title:"청년희망적금 가입·만기 확인", category:"금융·자산", amount:"신규 가입 종료 · 기존 가입자 만기 확인", organization:"금융위원회·서민금융진흥원", status:"closed", checkedAt:"2026-09-02 09:10", sourceUrl:"https://www.gov.kr/portal/service/serviceInfo/12100000372", applicationUrl:"https://www.gov.kr/portal/service/serviceInfo/12100000372", officialUrl:"https://www.gov.kr/portal/service/serviceInfo/12100000372", conditionSummary:"2001년생 취준생의 신규 가입 상품이 아니라 기존 가입·만기·이자소득 확인 후보", requirements:["기존 가입 여부 확인","만기일·납입 내역 확인","상품 종료 여부 공식 확인"], evidence:["가입 확인서","납입 내역","만기 안내"], isDemo:true },
  { id:"future-tomorrow-experience", title:"미래내일 일경험 인턴형", category:"일경험·취업", amount:"프로그램별 수련·일경험 지원", organization:"고용노동부·청년일경험 포털", status:"open", checkedAt:"2026-09-02 09:20", sourceUrl:"https://yw.work24.go.kr/main.do", applicationUrl:"https://yw.work24.go.kr/main.do", officialUrl:"https://yw.work24.go.kr/main.do", conditionSummary:"대학교 4학년·미취업·취업 준비 프로필과 인턴형 일경험 공고를 확인", requirements:["공고별 연령·재학 조건 확인","프로그램별 사전교육 확인","모집기간과 일경험 기간 확인"], evidence:["재학증명서","이력서","참여 신청 확인"], isDemo:true }
];
const SEED_EVENTS = [
  { id:"event-interview", title:"안랩 PM 면접", date:"2026-09-04", description:"판교 오프라인 면접. 면접확인서 요청 필요 가능성.", type:"interview", confidence:.93, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} },
  { id:"event-exam", title:"정보보안기사 필기", date:"2026-09-19", description:"9월 시험 응시료 결제 영수증과 접수 메일 저장 필요.", type:"exam", confidence:.97, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} },
  { id:"event-language", title:"토익 응시료 결제", date:"2026-09-12", description:"시험 접수와 결제 영수증을 보관합니다.", type:"exam", confidence:.86, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} },
  { id:"event-basic-income", title:"하남시 청년기본소득 3분기 신청 확인", date:"2026-09-08", description:"2001년생 가상 사용자 · 25만원 지급 대상 출생일 구간과 거주기간 확인.", type:"general", confidence:.78, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} },
  { id:"event-intern", title:"미래내일 일경험 인턴 공고 확인", date:"2026-09-15", description:"대학교 4학년 취업준비생에게 맞는 인턴형 일경험 모집기간과 사전교육을 확인.", type:"general", confidence:.8, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} },
  { id:"event-savings", title:"청년희망적금 만기·가입 이력 확인", date:"2026-09-23", description:"신규 가입이 아닌 기존 가입자용 만기와 납입 내역을 확인.", type:"general", confidence:.82, classificationSource:"local", channel:"seed", recovery:{hasPrimary:false, alternatives:[]} }
];
const RECOVERY_OPTIONS = {
  interview:[{id:"invite-email",label:"면접 안내 이메일"},{id:"job-post",label:"채용공고 캡처"},{id:"result-email",label:"면접 결과 안내"},{id:"business-card",label:"현장 명함"},{id:"onsite-photo",label:"현장 사진"}],
  exam:[{id:"receipt",label:"결제 영수증"},{id:"application-email",label:"접수 확인"},{id:"score-report",label:"응시 사실"},{id:"card-history",label:"카드 승인 내역"}]
};
const CALENDAR_CONNECTION_STATES = Object.freeze(["not-configured", "pending", "synced", "denied", "error"]);
const NOTIFICATION_CHANNELS = Object.freeze(["web", "email", "sms", "kakao"]);
const NOTIFICATION_OFFSETS = Object.freeze([7, 3, 1, 0, -1]);
const DEMO_PHONE = "010-****-0426";
const createAdapter = (name, methods = {}) => Object.freeze({name, ...methods});
const CalendarProviderAdapter = Object.freeze({contract:"CalendarProviderAdapter", required:["getStatus","connect","sync"]});
const GoogleCalendarAdapter = createAdapter("google", {
  getStatus: config => config?.oauthConfigured ? {state:"pending",label:"연결 대기",demo:true} : {state:"not-configured",label:"서버 설정 필요",demo:true},
  connect: config => config?.oauthConfigured ? {state:"pending",message:"OAuth 연결을 시작합니다. 콜백은 서버에서 처리합니다."} : {state:"not-configured",message:"Google OAuth client 설정이 필요합니다."},
  sync: outcome => outcome === "denied" ? {state:"denied",label:"권한 거부(가상)",demo:true} : outcome === "success" ? {state:"synced",label:"동기화 성공(가상)",demo:true,events:clone(SEED_EVENTS)} : {state:"error",label:"동기화 실패(가상)",demo:true}
});
const IcsImportAdapter = createAdapter("ics", {parse: input => parseICSWithWarnings(input)});
const CalenfitCalendarAdapter = createAdapter("calenfit", {
  getStatus: () => ({state:"synced",label:"자체 캘린더 활성",demo:true}),
  connect: () => ({state:"synced",label:"자체 캘린더 활성",demo:true}),
  sync: state => ({state:"synced",label:`자체 일정 ${state?.events?.length || 0}건`,demo:true})
});
const AIAnalysisAdapter = Object.freeze({contract:"AIAnalysisAdapter", allowedInput:["title","description","startTime"], allowedOutput:["type","confidence","rationale","evidenceCandidates"]});
const LocalSafeAIAnalysisAdapter = createAdapter("local", {analyze: event => { const result=inferEventType(event?.title||"",event?.description||""); return {type:result.type,confidence:result.confidence,rationale:result.fallbackReason||`${event?.title||"일정"}의 키워드에서 후보 유형을 분류했습니다.`,evidenceCandidates:result.type==="interview"?["면접 안내 이메일","채용공고"]:result.type==="exam"?["결제 영수증","접수 확인"]:[]}; }});
const PolicySourceAdapter = Object.freeze({contract:"PolicySourceAdapter", snapshot:policies => policies.map(normalizePolicy)});
const NotificationChannelAdapter = Object.freeze({contract:"NotificationChannelAdapter", channels:["web","email","sms","kakao"]});
const NotificationAdapters = Object.freeze({
  web:createAdapter("web", {schedule: payload => ({status:"scheduled",channel:"web",payload})}),
  email:createAdapter("email", {schedule: payload => ({status:"blocked",channel:"email",reason:"서버 메일 자격증명 필요",payload})}),
  sms:createAdapter("sms", {schedule: payload => ({status:"blocked",channel:"sms",reason:"서버 서명키와 수신 동의 필요",payload})}),
  kakao:createAdapter("kakao", {schedule: payload => ({status:"blocked",channel:"kakao",reason:"BizMessage 템플릿 승인·수신 동의·사업자 서버 필요",payload})})
});
const clone = value => JSON.parse(JSON.stringify(value));
const createEventId = () => `event-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
const createEvidenceId = () => `evidence-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;
const eventTypeLabel = type => ({interview:"면접",exam:"시험",startup:"창업",general:"일반"}[type] || "일반");
const statusLabel = level => ({high:"가능성 높음",medium:"확인 필요",low:"현재 대상 아님"}[level] || "확인 필요");
const policyStatusLabel = status => ({open:"접수 중",closed:"마감",exhausted:"예산 소진",unknown:"확인 필요",review:"확인 필요"}[status] || "확인 필요");
const isoDate = date => date.toISOString().slice(0,10);
const formatDate = value => new Intl.DateTimeFormat("ko-KR",{month:"short",day:"numeric",weekday:"short"}).format(new Date(`${value}T09:00:00+09:00`));
const diffDays = (value, base=today) => Math.round((new Date(`${value}T09:00:00+09:00`)-base)/86400000);
const validDate = value => /^\d{4}-\d{2}-\d{2}$/.test(String(value||"")) && !Number.isNaN(new Date(`${value}T09:00:00+09:00`).getTime()) && isoDate(new Date(`${value}T09:00:00+09:00`))===value;
const escapeHTML = value => String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ALLOWED_EXTERNAL_HOSTS = new Set(["gg.go.kr","www.gg.go.kr","web1.gg.go.kr","youth.gg.go.kr","apply.jobaba.net","hanam.go.kr","www.hanam.go.kr","gov.kr","www.gov.kr","yw.work24.go.kr"]);
const safeUrl = value => { try { const url = new URL(String(value)); return url.protocol === "https:" && ALLOWED_EXTERNAL_HOSTS.has(url.hostname) ? url.href : ""; } catch (_) { return ""; } };
const isPlainObject = value => value !== null && typeof value === "object" && !Array.isArray(value) && (Object.getPrototypeOf(value) === Object.prototype || Object.getPrototypeOf(value) === null);

function inferEventType(title="",description="") { const text=`${title} ${description}`.toLowerCase(); if(/면접|interview|채용/.test(text)) return {type:"interview",confidence:.84,source:"local"}; if(/기사|toeic|토익|시험|exam|자격/.test(text)) return {type:"exam",confidence:.86,source:"local"}; if(/창업|startup|demo day|데모데이/.test(text)) return {type:"startup",confidence:.72,source:"local"}; return {type:"general",confidence:.55,source:"local",fallbackReason:"규칙에 맞는 키워드가 없어 일반 일정으로 분류했습니다."}; }
function classifyEvent(title,description="",adapter) { const allowed=new Set(["interview","exam","startup","general"]); if(adapter&&typeof adapter.classify==="function") try { const result=adapter.classify({title:String(title),description:String(description)}); if(!result||!allowed.has(result.type)||!Number.isFinite(Number(result.confidence))||Number(result.confidence)<0||Number(result.confidence)>1) throw new Error("AI 분류 응답 형식이 올바르지 않습니다."); return {type:result.type,confidence:Number(result.confidence),source:"ai"}; } catch(error) { return {...inferEventType(title,description),fallback:true,fallbackReason:`AI 분류 실패 — 로컬 안전 분류 사용 (${error?.message||"오류"})`}; } return inferEventType(title,description); }
function normalizePolicy(policy) { const known=SEED_POLICIES.find(item=>item.id===policy?.id)||{}; const sourceUrl=safeUrl(policy?.sourceUrl), applicationUrl=safeUrl(policy?.applicationUrl||policy?.officialUrl), checkedAt=String(policy?.checkedAt||"").trim(), status=sourceUrl&&checkedAt&&POLICY_STATES.includes(policy?.status)?policy.status:"unknown"; return {...clone(known),...clone(policy||{}),status,sourceUrl,applicationUrl,officialUrl:applicationUrl,checkedAt:checkedAt||"확인 시각 없음",isDemo:true,requirements:Array.isArray(policy?.requirements)?policy.requirements.filter(item=>typeof item==="string").slice(0,20):clone(known.requirements||[]),evidence:Array.isArray(policy?.evidence)?policy.evidence.filter(item=>typeof item==="string").slice(0,20):clone(known.evidence||[])}; }
function matchPolicy(policy,event,profile=PROFILE){if(!policy||!event)return null;const title=String(event.title||"");if(policy.id==="hanam-basic-income"){if(event.type!=="general"||(!title.includes("청년기본소득")&&event.id!=="event-basic-income"))return null;if(!String(profile.residence||"").includes("하남"))return {eligibility:"low",reason:"하남시 주민등록 조건을 충족하지 않습니다."};return {eligibility:"medium",reason:"2001년생·하남시 가상 프로필과 연결했지만 정확한 생년월일·거주기간 심사가 필요합니다."};}if(policy.id==="youth-hope-savings"){if(event.type!=="general"||!title.includes("희망적금"))return null;return {eligibility:"medium",reason:"2001년생 금융 관심 후보지만 신규 가입 가능 여부와 기존 가입·만기 상태를 확인해야 합니다."};}if(policy.id==="future-tomorrow-experience"){if(event.type!=="general"||!title.includes("일경험"))return null;return {eligibility:profile.status==="미취업"?"medium":"low",reason:"대학교 4학년·취업 준비·미취업 프로필과 일경험 공고를 연결했지만 공고별 선발 조건을 확인해야 합니다."};}if(policy.id==="interview-allowance"||policy.id==="exam-support"){if((policy.id==="interview-allowance"&&event.type!=="interview")||(policy.id==="exam-support"&&event.type!=="exam"))return null;if(!String(profile.residence||"").includes("경기도"))return {eligibility:"low",reason:"경기도 거주 조건을 충족하지 않습니다."};if(policy.id==="interview-allowance"&&profile.status!=="미취업")return {eligibility:"medium",reason:"재직 여부를 운영기관 기준으로 추가 확인해야 합니다."};return {eligibility:"high",reason:policy.id==="interview-allowance"?"경기도 거주·미취업 프로필과 면접 일정이 핵심 조건에 부합합니다.":"경기도 거주 프로필과 자격시험 일정이 연결됩니다."};}return null;}
function matchPolicies(event,policies=SEED_POLICIES,profile=PROFILE) { return policies.filter(policy=>POLICY_IDS.includes(policy.id)).map(policy=>{const result=matchPolicy(policy,event,profile); return result?{policy:normalizePolicy(policy),...result}:null;}).filter(Boolean); }
function buildTasks(event,matches=[],base=today) { if(!event) return []; const eventDate=new Date(`${event.date}T09:00:00+09:00`); const add=(offset,kind,title,body,extra={})=>{const due=new Date(eventDate); due.setDate(due.getDate()+offset); return {id:`${event.id}:${kind}:${isoDate(due)}`,eventId:event.id,kind,title,due:isoDate(due),body,completed:false,...extra};}; let tasks=[]; if(event.type==="interview") tasks=[add(-3,"before-3","채용공고·면접 안내 저장","면접 안내 이메일과 채용공고를 원본 그대로 보관합니다."),add(1,"after-1","면접확인서 요청","면접 다음 날 확인서 요청 초안을 보내고 회신을 기록합니다."),add(3,"after-3","확인서 미회신 후속","회신이 없으면 대체 증빙과 공식 안내 경로를 확인합니다.")]; else if(event.type==="exam") tasks=[add(-3,"receipt","결제영수증·접수확인 보관","결제 영수증과 접수 확인을 함께 보관합니다."),add(0,"attendance","응시 사실 보존","수험표나 응시 확인 화면을 남깁니다."),add(1,"employment-status","응시일 취업 상태 기록","신청 시 요구될 수 있는 취업 상태를 확인합니다.")]; for(const {policy} of matches){const p=normalizePolicy(policy); if(validDate(p.applicationStart)) tasks.push(add(diffDays(p.applicationStart,eventDate),`policy-start-${p.id}`,"접수 시작",`${p.title} 공식 접수 시작일을 확인합니다.`,{policyId:p.id,provenance:{sourceUrl:p.sourceUrl,checkedAt:p.checkedAt}})); if(validDate(p.applicationDeadline)) tasks.push(add(diffDays(p.applicationDeadline,eventDate),`policy-deadline-${p.id}`,"마감 임박",`${p.title} 신청 마감일과 제출 조건을 확인합니다.`,{policyId:p.id,provenance:{sourceUrl:p.sourceUrl,checkedAt:p.checkedAt}})); } return tasks.map(task=>{const days=diffDays(task.due,base); return {...task,overdue:days<0,state:days<0?"overdue":days<=3?"urgent":"soon"};}); }

function parseICSDate(raw,params={}) { const value=String(raw||"").trim(); if(/^\d{8}$/.test(value)){const date=`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`; if(!validDate(date)) throw new Error("ICS 날짜가 올바르지 않습니다."); return {date,timezoneWarning:false};} if(/^\d{8}T\d{6}Z$/.test(value)){const date=`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`; if(!validDate(date)) throw new Error("ICS 날짜가 올바르지 않습니다."); return {date,timezoneWarning:false};} if(/^\d{8}T\d{6}$/.test(value)){const date=`${value.slice(0,4)}-${value.slice(4,6)}-${value.slice(6,8)}`; if(!validDate(date)) throw new Error("ICS 날짜가 올바르지 않습니다."); const tz=String(params.TZID||""); const supported=new Set(["Asia/Seoul","Asia/Tokyo","UTC","Etc/UTC"]); return {date,timezoneWarning:!tz||!supported.has(tz)};} throw new Error("ICS DTSTART는 YYYYMMDD 또는 YYYYMMDDTHHMMSS 형식이어야 합니다."); }
function parseICSWithWarnings(input) { if(typeof input!=="string"||input.length>2*1024*1024||!input.trim()) throw new Error("ICS 파일이 비어 있거나 너무 큽니다."); const lines=input.replace(/\r?\n[ \t]/g,"").split(/\r?\n/).filter(Boolean); if(lines[0]!=="BEGIN:VCALENDAR"||!lines.includes("END:VCALENDAR")) throw new Error("유효한 VCALENDAR 컨테이너가 없습니다."); const blocks=[]; let current=null; for(const line of lines){if(line==="BEGIN:VEVENT"){if(current)throw new Error("ICS VEVENT가 중첩되었습니다."); current={}; continue;} if(line==="END:VEVENT"){if(!current)throw new Error("ICS VEVENT 종료가 올바르지 않습니다."); blocks.push(current); current=null; continue;} if(!current) continue; const colon=line.indexOf(":"); if(colon<1) throw new Error("ICS 속성 형식이 올바르지 않습니다."); const parts=line.slice(0,colon).split(";"),key=parts.shift().toUpperCase(),params=Object.fromEntries(parts.map(part=>{const [k,v]=part.split("="); return [String(k).toUpperCase(),String(v||"")];})); current[key]={value:line.slice(colon+1).replace(/\\n/gi,"\n").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\"),params}; } if(current||!blocks.length) throw new Error("ICS에서 VEVENT를 찾지 못했습니다."); let timezoneWarning=false; const events=blocks.map((item,index)=>{const summary=item.SUMMARY?.value?.trim(); if(!summary)throw new Error(`ICS 일정 ${index+1}에 제목이 없습니다.`); if(!item.DTSTART)throw new Error(`ICS 일정 ${index+1}에 DTSTART가 없습니다.`); const parsed=parseICSDate(item.DTSTART.value,item.DTSTART.params); timezoneWarning ||= parsed.timezoneWarning; const inferred=inferEventType(summary,item.DESCRIPTION?.value||""); return {id:createEventId(),title:summary,date:parsed.date,description:item.DESCRIPTION?.value||"",type:inferred.type,confidence:inferred.confidence,classificationSource:"local",channel:"ics",recovery:{hasPrimary:false,alternatives:[]},timezoneWarning:parsed.timezoneWarning};}); events.warnings=timezoneWarning?["시간대가 명확하지 않은 DTSTART가 있습니다. 날짜를 확인한 뒤 가져오세요."]:[]; return events; }
function parseICS(input){return parseICSWithWarnings(input);}
function evaluateRecovery(event) { const options=RECOVERY_OPTIONS[event?.type]||[],selected=new Set(event?.recovery?.alternatives||[]),primary=Boolean(event?.recovery?.hasPrimary),count=selected.size+(primary?1:0),minimum=event?.type==="interview"?2:1,missing=options.filter(option=>!selected.has(option.id)).map(option=>option.label),acquired=options.filter(option=>selected.has(option.id)).map(option=>option.label),status=primary?"sufficient":selected.size>=minimum?"alternative":"incomplete"; return {status,label:primary?"핵심 증빙 확보":status==="alternative"?"대체 신청 경로 있음":"추가 확인 필요",count,acquired,missing:primary?[]:missing,nextAction:primary?"공식 신청 페이지 · 공식 공고 확인의 제출 요건을 확인한 뒤 제출하세요.":status==="alternative"?"대체 증빙 조합을 운영기관에 확인하세요.":"증빙을 더 확보한 뒤 운영기관 안내를 확인하세요.",disclaimer:status==="alternative"?"대체 경로 인정 여부는 운영기관 최종 판단입니다.":"최종 판단은 운영기관이 합니다.",safetyStatements:[{label:"대체 신청 경로 있음",active:status==="alternative"||primary},{label:"추가 확인 필요",active:status==="incomplete"},{label:"최종 판단은 운영기관",active:true}]}; }
function seedState(){return {schemaVersion:SCHEMA_VERSION,version:SCHEMA_VERSION,profile:clone(PROFILE),policies:clone(SEED_POLICIES),events:clone(SEED_EVENTS),taskCompletion:{},evidenceFiles:[],calendarConnections:{calenfit:{state:"synced",label:"자체 캘린더 활성",lastSync:"2026-09-01 09:00"},ics:{state:"not-configured",label:"파일 선택 필요"},google:{state:"not-configured",label:"서버 설정 필요"}},notifications:[],selectedEventId:"event-interview",error:"",notice:""};}
function emptyState(){return {schemaVersion:SCHEMA_VERSION,version:SCHEMA_VERSION,profile:{age:"—",birthYear:"—",residence:"로그인 필요",status:"로그인 필요",education:"로그인 필요",goal:"로그인 필요"},policies:[],events:[],taskCompletion:{},evidenceFiles:[],calendarConnections:{calenfit:{state:"not-connected",label:"연결되지 않음"},ics:{state:"not-configured",label:"파일 선택 필요"},google:{state:"not-configured",label:"로그인 필요"}},notifications:[],selectedEventId:null,error:"",notice:"",auth:{isLoggedIn:false,mode:"anonymous"}};}
function validateState(value){if(!value||value.schemaVersion!==SCHEMA_VERSION||value.version!==SCHEMA_VERSION||!Array.isArray(value.events)||!Array.isArray(value.policies)||!Array.isArray(value.evidenceFiles)||!isPlainObject(value.taskCompletion)) throw new Error("호환되지 않는 저장 데이터입니다."); const profile=isPlainObject(value.profile)?{...PROFILE,age:Number.isFinite(Number(value.profile.age))?Number(value.profile.age):PROFILE.age,residence:String(value.profile.residence||PROFILE.residence).slice(0,120),status:String(value.profile.status||PROFILE.status).slice(0,60),isDemo:true}:clone(PROFILE); const events=value.events.filter(event=>event&&typeof event.id==="string"&&validDate(event.date)).map(event=>({...event,title:String(event.title||"일정").slice(0,200),description:String(event.description||"").slice(0,2000),type:["interview","exam","startup","general"].includes(event.type)?event.type:"general",recovery:{hasPrimary:Boolean(event.recovery?.hasPrimary),alternatives:Array.isArray(event.recovery?.alternatives)?event.recovery.alternatives.filter(item=>typeof item==="string").slice(0,20):[]}}));const eventIds=new Set(events.map(event=>event.id));const evidenceFiles=value.evidenceFiles.filter(file=>file&&typeof file.id==="string"&&typeof file.name==="string"&&Number.isFinite(Number(file.size))&&Number(file.size)>=0&&Number(file.size)<=MAX_EVIDENCE_BYTES&&Number.isFinite(Number(file.lastModified))).map(file=>({id:String(file.id).slice(0,120),name:String(file.name).slice(0,240),type:String(file.type||"unknown").slice(0,120),size:Number(file.size),lastModified:Number(file.lastModified),eventId:typeof file.eventId==="string"&&eventIds.has(file.eventId)?file.eventId:null,hints:Array.isArray(file.hints)?file.hints.filter(item=>typeof item==="string").map(item=>item.slice(0,120)).slice(0,10):["수동 확인 필요"]})); const state={...seedState(),...clone(value),profile,policies:value.policies.filter(policy=>POLICY_IDS.includes(policy.id)).map(normalizePolicy),events,evidenceFiles,taskCompletion:Object.fromEntries(Object.entries(value.taskCompletion).filter(([key,val])=>typeof key==="string"&&typeof val==="boolean"))}; if(!state.policies.length)state.policies=clone(SEED_POLICIES); return state;}
function loadState(storage=globalThis.localStorage){try{const raw=typeof storage?.getItem==="function"?storage.getItem(STORAGE_KEY):null; return raw?validateState(JSON.parse(raw)):seedState();}catch(error){const state=seedState(); state.error=`저장 데이터를 불러오지 못해 데모 데이터를 사용합니다. ${error?.message||""}`.trim(); return state;}}
function saveState(appState,storage=globalThis.localStorage){appState.schemaVersion=SCHEMA_VERSION;appState.version=SCHEMA_VERSION;try{if(typeof storage?.setItem==="function")storage.setItem(STORAGE_KEY,JSON.stringify(validateState(appState)));appState.error="";return appState;}catch(error){appState.error=`로컬 저장에 실패했습니다. 현재 화면에서 계속할 수 있지만 새로고침하면 사라질 수 있습니다. ${error?.message||""}`.trim();return appState;}}
function resetState(storage=globalThis.localStorage){const fresh=seedState();try{if(typeof storage?.removeItem==="function")storage.removeItem(STORAGE_KEY);if(typeof storage?.setItem==="function")storage.setItem(STORAGE_KEY,JSON.stringify(fresh));}catch(error){fresh.error=`초기화 저장에 실패했습니다. ${error?.message||""}`;}return fresh;}
function setTaskCompletion(appState,taskId,completed,storage){appState.taskCompletion[String(taskId)]=Boolean(completed);return saveState(appState,storage);}
function createEvent(appState,data,adapter,storage){const title=String(data?.title||"").trim(),date=String(data?.date||"");if(!title||title.length>200||!validDate(date))throw new Error("일정 제목(200자 이내)과 올바른 날짜를 입력해 주세요.");const description=String(data?.description||"").trim().slice(0,2000),result=data?.type&&data.type!=="auto"?{type:["interview","exam","startup","general"].includes(data.type)?data.type:"general",confidence:1,source:"user"}:classifyEvent(title,description,adapter),event={id:createEventId(),title,date,description,type:result.type,confidence:result.confidence,classificationSource:result.source||"local",channel:data?.channel||"manual",recovery:{hasPrimary:false,alternatives:[]}};appState.events.push(event);appState.selectedEventId=event.id;if(result.fallbackReason)appState.notice=result.fallbackReason;saveState(appState,storage);return event;}
function updateEvent(appState,id,patch,adapter,storage){const event=appState.events.find(item=>item.id===id);if(!event)throw new Error("일정을 찾을 수 없습니다.");Object.keys(appState.taskCompletion).filter(key=>key.startsWith(`${id}:`)).forEach(key=>delete appState.taskCompletion[key]);if(patch.title!==undefined){const title=String(patch.title).trim();if(!title||title.length>200)throw new Error("일정 제목을 확인해 주세요.");event.title=title;}if(patch.date!==undefined){if(!validDate(patch.date))throw new Error("일정 날짜를 확인해 주세요.");event.date=patch.date;}if(patch.description!==undefined)event.description=String(patch.description).trim().slice(0,2000);if(patch.type!==undefined){if(patch.type&&["interview","exam","startup","general"].includes(patch.type)){event.type=patch.type;event.confidence=1;event.classificationSource="user";}else if(patch.type==="auto"){const result=classifyEvent(event.title,event.description,adapter);Object.assign(event,{type:result.type,confidence:result.confidence,classificationSource:result.source});if(result.fallbackReason)appState.notice=result.fallbackReason;}}else if(patch.title!==undefined||patch.description!==undefined){const result=classifyEvent(event.title,event.description,adapter);Object.assign(event,{type:result.type,confidence:result.confidence,classificationSource:result.source});if(result.fallbackReason)appState.notice=result.fallbackReason;}return saveState(appState,storage);}
function deleteEvent(appState,id,storage){if(!appState.events.some(event=>event.id===id))throw new Error("일정을 찾을 수 없습니다.");appState.events=appState.events.filter(event=>event.id!==id);appState.evidenceFiles=appState.evidenceFiles.filter(file=>file.eventId!==id);Object.keys(appState.taskCompletion).filter(key=>key.startsWith(`${id}:`)).forEach(key=>delete appState.taskCompletion[key]);if(appState.selectedEventId===id)appState.selectedEventId=appState.events[0]?.id||null;return saveState(appState,storage);}
function extractEvidenceHints(file){const name=String(file?.name||"").toLowerCase(),hints=[];if(/면접|interview/.test(name))hints.push("면접 관련 파일명 힌트");if(/영수증|receipt|결제/.test(name))hints.push("영수증 후보 파일명 힌트");if(/응시|시험|기사|exam/.test(name))hints.push("시험 관련 파일명 힌트");if(/\.pdf$/.test(name))hints.push("문서형 파일명 힌트");return hints.length?hints:["수동 확인 필요"];}
function addEvidence(appState,file,eventId,storage){const name=String(file?.name||"").trim(),type=String(file?.type||"").toLowerCase(),size=Number(file?.size),extensionOK=/\.(pdf|png|jpe?g|gif|webp)$/i.test(name);if(!name||(!type.startsWith("image/")&&type!=="application/pdf"&&!extensionOK))throw new Error("지원 형식은 이미지 또는 PDF입니다.");if(!Number.isFinite(size)||size<0||size>MAX_EVIDENCE_BYTES)throw new Error("증빙 파일은 10MiB 이하만 추가할 수 있습니다.");const meta={id:createEvidenceId(),name:name.slice(0,240),type:type||"application/octet-stream",size,lastModified:Number(file.lastModified)||Date.now(),eventId:eventId||appState.selectedEventId,hints:extractEvidenceHints(file)};appState.evidenceFiles.push(meta);saveState(appState,storage);return meta;}
function buildNotificationPayload(event, offset, channel="web"){const days=Number(offset), label=days>0?`D-${days}`:days===0?"당일":"D+1";return {id:`${event?.id||"event"}:notification:${days}:${channel}`,eventId:event?.id||null,channel,offset:days,label,title:`${event?.title||"일정"} ${label} 확인`,body:"증빙 행동과 공식 정책 상태를 확인하세요.",phone:channel==="sms"||channel==="kakao"?DEMO_PHONE:undefined};}
function scheduleNotification(appState,{eventId,channel="web",offset=3,consent=false}={}){const event=appState.events.find(item=>item.id===eventId)||appState.events[0];if(!event)throw new Error("알림을 연결할 일정이 없습니다.");if(!NOTIFICATION_CHANNELS.includes(channel))throw new Error("지원하지 않는 알림 채널입니다.");const payload=buildNotificationPayload(event,offset,channel);const result=!consent?{status:"blocked",channel,reason:"수신 동의가 필요합니다.",payload}:NotificationAdapters[channel].schedule(payload);const record={...result,consent:Boolean(consent),createdAt:"2026-09-01 09:00",demo:true};appState.notifications=Array.isArray(appState.notifications)?appState.notifications.filter(item=>item.id!==payload.id):[];appState.notifications.push({...record,id:payload.id});saveState(appState);return record;}
function calendarConnectionSummary(state){const connections=state?.calendarConnections||{};return [
  {id:"calenfit",name:"자체 캘린더",state:connections.calenfit?.state||"synced",label:connections.calenfit?.label||"자체 캘린더 활성"},
  {id:"ics",name:"ICS 가져오기",state:state?.events?.some(item=>item.channel==="ics")?"synced":connections.ics?.state||"not-configured",label:state?.events?.some(item=>item.channel==="ics")?"가져오기 완료(로컬)":connections.ics?.label||"파일 선택 필요"},
  {id:"google",name:"Google Calendar",state:connections.google?.state||"not-configured",label:connections.google?.label||"서버 설정 필요"}
];}

function buildEmailDraft(event){return `제목: ${String(event?.title||"면접").slice(0,200)} 확인 요청\n\n안녕하세요. ${String(event?.date||"").slice(0,10)} 일정의 참석 확인을 부탁드립니다.`;}


if (typeof module !== "undefined") {
  module.exports = {
    STORAGE_KEY, SCHEMA_VERSION, PROFILE, SEED_POLICIES, SEED_EVENTS, RECOVERY_OPTIONS,
    MAX_EVIDENCE_BYTES, inferEventType, classifyEvent, normalizePolicy, parseICS,
    parseICSWithWarnings, matchPolicy, matchPolicies, buildTasks, evaluateRecovery,
    seedState, validateState, loadState, saveState, resetState, setTaskCompletion,
    createEvent, updateEvent, deleteEvent, addEvidence, extractEvidenceHints, formatDate,
    diffDays, policyStatusLabel, statusLabel, eventTypeLabel, validDate, safeUrl,
    CalendarProviderAdapter, GoogleCalendarAdapter, IcsImportAdapter,
    CalenfitCalendarAdapter, AIAnalysisAdapter, LocalSafeAIAnalysisAdapter,
    PolicySourceAdapter, NotificationChannelAdapter, NotificationAdapters,
    CALENDAR_CONNECTION_STATES, NOTIFICATION_CHANNELS, NOTIFICATION_OFFSETS,
    DEMO_PHONE, buildNotificationPayload, scheduleNotification, calendarConnectionSummary,
    buildEmailDraft,
  };
}
