import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { createServer } from "node:http";
import { readFile } from "node:fs/promises";
import { extname, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)));
const PORT = Number(process.env.PORT || 8000);
const SESSION_SECRET = process.env.CALENFIT_SESSION_SECRET || randomBytes(32).toString("hex");
const sessions = new Map();
const users = new Map();
const oauthStates = new Map();
const googleTokens = new Map();
const json = value => JSON.stringify(value);
const send = (response, status, body, headers = {}) => { response.writeHead(status, { "content-type": "application/json; charset=utf-8", ...headers }); response.end(json(body)); };
const readBody = request => new Promise((resolveBody, reject) => { let raw = ""; request.on("data", chunk => { raw += chunk; if (raw.length > 1000000) reject(new Error("request too large")); }); request.on("end", () => { try { resolveBody(raw ? JSON.parse(raw) : {}); } catch { reject(new Error("invalid JSON")); } }); request.on("error", reject); });
const cookie = (request, name) => String(request.headers.cookie || "").split(";").map(item => item.trim().split("=")).find(item => item[0] === name)?.[1] || "";
const sessionCookie = token => `calenfit_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400${process.env.NODE_ENV === "production" ? "; Secure" : ""}`;
const issueSession = (profile, meta = {}) => { const id = randomBytes(32).toString("base64url"); const signature = createHmac("sha256", SESSION_SECRET).update(id).digest("base64url"); const token = `${id}.${signature}`; sessions.set(id, { ...meta, profile, createdAt: Date.now() }); return { token, id }; };
const currentSession = request => { const token = cookie(request, "calenfit_session"), [id, signature] = token.split("."); if (!id || !signature || sessions.get(id) === undefined) return null; const expected = createHmac("sha256", SESSION_SECRET).update(id).digest("base64url"); if (signature.length !== expected.length || !timingSafeEqual(Buffer.from(signature), Buffer.from(expected))) return null; return { id, record: sessions.get(id) }; };
const normalizeProfile = value => ({ birthYear: Number(value.birthYear) || 2001, residence: String(value.residence || "").slice(0, 120), status: String(value.status || "미취업").slice(0, 40), education: String(value.education || "").slice(0, 80), goal: String(value.goal || "").slice(0, 80) });
const passwordHash = password => { const salt = randomBytes(16); return `${salt.toString("base64url")}.${scryptSync(String(password), salt, 32).toString("base64url")}`; };
const passwordMatches = (password, stored) => { try { const [saltText, digestText] = String(stored).split("."); const salt = Buffer.from(saltText, "base64url"); const digest = Buffer.from(digestText, "base64url"); const actual = scryptSync(String(password), salt, 32); return digest.length === actual.length && timingSafeEqual(digest, actual); } catch { return false; } };
const validCredentials = (email, password) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && String(password).length >= 10;
const secretKey = createHash("sha256").update(SESSION_SECRET).digest();
const encryptSecret = value => { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", secretKey, iv); const encrypted = Buffer.concat([cipher.update(String(value || ""), "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; };
const decryptSecret = value => { const [ivText, tagText, encryptedText] = String(value || "").split("."); const decipher = createDecipheriv("aes-256-gcm", secretKey, Buffer.from(ivText, "base64url")); decipher.setAuthTag(Buffer.from(tagText, "base64url")); return Buffer.concat([decipher.update(Buffer.from(encryptedText, "base64url")), decipher.final()]).toString("utf8"); };
const contentType = file => ({ ".html":"text/html; charset=utf-8", ".css":"text/css; charset=utf-8", ".js":"text/javascript; charset=utf-8", ".mjs":"text/javascript; charset=utf-8", ".json":"application/json; charset=utf-8" }[extname(file).toLowerCase()] || "application/octet-stream");
async function serveStatic(request, response) { const pathname = decodeURIComponent(new URL(request.url || "/", "http://localhost").pathname); const relative = pathname === "/" ? "index.html" : pathname.slice(1); const file = resolve(ROOT, relative); if (file !== ROOT && !file.startsWith(`${ROOT}${sep}`)) return send(response, 403, { error: "forbidden" }); try { const body = await readFile(file); response.writeHead(200, { "content-type": contentType(file), "cache-control": "no-store" }); response.end(body); } catch (error) { send(response, error.code === "ENOENT" ? 404 : 500, { error: error.code === "ENOENT" ? "not found" : "server error" }); } }
async function handle(request, response) { const url = new URL(request.url || "/", "http://localhost"); try {
  if (request.method === "POST" && url.pathname === "/api/auth/demo") { const body = await readBody(request); const profile = normalizeProfile(body.profile); const session = issueSession(profile, { mode: "demo", userId: createHash("sha256").update(String(profile.birthYear)+String(profile.residence)).digest("hex").slice(0, 16) }); return send(response, 200, { user: { id: createHash("sha256").update(session.id).digest("hex").slice(0, 16), mode: "demo", profile }, session: { expiresIn: 86400 } }, { "set-cookie": sessionCookie(session.token) }); }
  if (request.method === "POST" && ["/api/auth/signup", "/api/auth/login"].includes(url.pathname)) { const body = await readBody(request); const email = String(body.email || "").trim().toLowerCase(); const password = String(body.password || ""); if (!validCredentials(email, password)) return send(response, 400, { error: "이메일 형식과 10자 이상 비밀번호를 확인하세요." }); const existing = users.get(email); if (url.pathname.endsWith("signup")) { if (existing) return send(response, 409, { error: "이미 가입된 이메일입니다." }); users.set(email, { password: passwordHash(password), profile: normalizeProfile(body.profile), createdAt: Date.now() }); } else if (!existing || !passwordMatches(password, existing.password)) return send(response, 401, { error: "이메일 또는 비밀번호가 올바르지 않습니다." }); const user = users.get(email); const session = issueSession(user.profile, { email, userId: createHash("sha256").update(email).digest("hex").slice(0, 16), mode: "account" }); user.sessionId = session.id; return send(response, 200, { user: { id: createHash("sha256").update(email).digest("hex").slice(0, 16), email, mode: "account", profile: user.profile }, session: { expiresIn: 86400 } }, { "set-cookie": sessionCookie(session.token) }); }
  if (request.method === "GET" && url.pathname === "/api/auth/session") { const session = currentSession(request); return send(response, session ? 200 : 401, session ? { user: { id: session.record.userId, email: session.record.email, mode: session.record.mode, profile: session.record.profile } } : { error: "not authenticated" }); }
  if (request.method === "POST" && url.pathname === "/api/auth/logout") { const session = currentSession(request); if (session) sessions.delete(session.id); return send(response, 200, { ok: true }, { "set-cookie": "calenfit_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0" }); }
  if (request.method === "POST" && url.pathname === "/api/profile") { const session = currentSession(request); if (!session) return send(response, 401, { error: "login required" }); const profile = normalizeProfile(await readBody(request)); session.record.profile = profile; if (session.record.email && users.get(session.record.email)) users.get(session.record.email).profile = profile; return send(response, 200, { profile }); }
  if (request.method === "GET" && url.pathname === "/api/calendar/google/connect") { const session = currentSession(request); if (!session) return send(response, 401, { error: "login required" }); if (!process.env.GOOGLE_CLIENT_ID || !process.env.GOOGLE_CLIENT_SECRET) return send(response, 503, { code: "GOOGLE_OAUTH_NOT_CONFIGURED", error: "Google OAuth server configuration is required" }); const state = randomBytes(24).toString("base64url"); const verifier = randomBytes(32).toString("base64url"); const challenge = createHash("sha256").update(verifier).digest("base64url"); oauthStates.set(state, { createdAt: Date.now(), verifier, sessionId: session.id }); const params = new URLSearchParams({ client_id: process.env.GOOGLE_CLIENT_ID, redirect_uri: process.env.GOOGLE_REDIRECT_URI || `http://localhost:${PORT}/api/calendar/google/callback`, response_type: "code", access_type: "offline", scope: "https://www.googleapis.com/auth/calendar.events.readonly", state, code_challenge: challenge, code_challenge_method: "S256" }); return send(response, 200, { authorizationUrl: `https://accounts.google.com/o/oauth2/v2/auth?${params}` }); }
  if (request.method === "GET" && url.pathname === "/api/calendar/google/callback") { const session = currentSession(request), state = url.searchParams.get("state"), code = url.searchParams.get("code"); const stateRecord = oauthStates.get(state); if (!session || !stateRecord || stateRecord.sessionId !== session.id || Date.now() - stateRecord.createdAt > 600000 || !code) return send(response, 400, { error: "invalid or expired OAuth state" }); oauthStates.delete(state); const tokenResponse = await fetch("https://oauth2.googleapis.com/token", { method: "POST", headers: { "content-type": "application/x-www-form-urlencoded" }, body: new URLSearchParams({ code, client_id: process.env.GOOGLE_CLIENT_ID, client_secret: process.env.GOOGLE_CLIENT_SECRET, redirect_uri: process.env.GOOGLE_REDIRECT_URI || `http://localhost:${PORT}/api/calendar/google/callback`, grant_type: "authorization_code", code_verifier: stateRecord.verifier }) }); if (!tokenResponse.ok) return send(response, 502, { error: "Google token exchange failed" }); const tokens = await tokenResponse.json(); if (!tokens.refresh_token && !tokens.access_token) return send(response, 502, { error: "Google returned no usable token" }); googleTokens.set(session.id, { accessToken: encryptSecret(tokens.access_token), refreshToken: tokens.refresh_token ? encryptSecret(tokens.refresh_token) : null, expiresAt: Date.now() + Number(tokens.expires_in || 3600) * 1000 }); response.writeHead(302, { location: "/?google=connected" }); return response.end(); }
  if (request.method === "GET" && url.pathname === "/api/calendar/status") { const session = currentSession(request); return send(response, 200, { provider: "google", state: session && googleTokens.has(session.id) ? "synced" : process.env.GOOGLE_CLIENT_ID && process.env.GOOGLE_CLIENT_SECRET ? "configured" : "not-configured" }); }
  if (request.method === "POST" && url.pathname === "/api/calendar/google/disconnect") { const session = currentSession(request); if (session) googleTokens.delete(session.id); return send(response, 200, { state: "disconnected" }); }
  if (request.method === "GET" && url.pathname === "/api/calendar/google/sync") { const session = currentSession(request), token = session && googleTokens.get(session.id); if (!token) return send(response, 401, { error: "Google calendar is not connected" }); let accessToken; try { accessToken = decryptSecret(token.accessToken); } catch { return send(response, 502, { error: "Stored Google token could not be decrypted" }); } const calendarResponse = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=true&orderBy=startTime&maxResults=100", { headers: { authorization: `Bearer ${accessToken}` } }); if (!calendarResponse.ok) return send(response, 502, { error: `Google calendar sync failed (${calendarResponse.status})` }); const body = await calendarResponse.json(); const events = (body.items || []).filter(item => item.status !== "cancelled").map(item => ({ providerId: item.id, title: String(item.summary || "일정").slice(0, 200), description: String(item.description || "").slice(0, 2000), startTime: item.start?.dateTime || item.start?.date || null, endTime: item.end?.dateTime || item.end?.date || null, source: "google" })); return send(response, 200, { events, nextSyncToken: body.nextSyncToken || null }); }
  if (request.method === "POST" && url.pathname === "/api/ai/analyze") { if (!process.env.XAI_API_KEY) return send(response, 503, { code: "GROK_NOT_CONFIGURED", error: "Grok proxy is not configured; use local fallback" }); const body = await readBody(request); const input = { title: String(body.input?.title || "").slice(0, 200), description: String(body.input?.description || "").slice(0, 2000), startTime: String(body.input?.startTime || "").slice(0, 80) }; const upstream = await fetch(process.env.XAI_API_URL || "https://api.x.ai/v1/chat/completions", { method: "POST", headers: { authorization: `Bearer ${process.env.XAI_API_KEY}`, "content-type": "application/json" }, body: json({ model: process.env.XAI_MODEL || "grok-4-1-fast-reasoning", temperature: 0, response_format: { type: "json_object" }, messages: [{ role: "system", content: "Return JSON only: type is one of interview, exam, startup, general; confidence 0..1; rationale short; evidenceCandidates string array. Never decide policy eligibility, amount, budget, status, or application." }, { role: "user", content: json(input) }] }) }); if (!upstream.ok) return send(response, 502, { code: "GROK_UPSTREAM_ERROR", error: `Grok proxy upstream ${upstream.status}` }); const result = await upstream.json(); let parsed; try { parsed = JSON.parse(result.choices?.[0]?.message?.content || "{}"); } catch { return send(response, 502, { code: "GROK_INVALID_JSON", error: "Grok returned invalid JSON" }); } if (!["interview", "exam", "startup", "general"].includes(parsed.type) || !Number.isFinite(Number(parsed.confidence))) return send(response, 502, { code: "GROK_INVALID_SCHEMA", error: "Grok response schema is invalid" }); return send(response, 200, { type: parsed.type, confidence: Number(parsed.confidence), rationale: String(parsed.rationale || "").slice(0, 300), evidenceCandidates: Array.isArray(parsed.evidenceCandidates) ? parsed.evidenceCandidates.filter(item => typeof item === "string").slice(0, 8) : [] }); }
  return serveStatic(request, response);
 } catch (error) { return send(response, 400, { error: error.message || "bad request" }); } }
createServer(handle).listen(PORT, () => console.log(`Calenfit server listening on http://localhost:${PORT}`));
