export const liveIntentCases = [
  { name: "interview-casual", title: "내일 대표님이랑 마지막으로 얘기함", description: "채용 프로세스 최종 대면 미팅", expectedAny: ["employment"] },
  { name: "internship-orientation", title: "회사 체험 첫날 OT", description: "청년 일경험 프로그램 사전교육", expectedAny: ["work-experience"], allowedExtra: ["education", "employment"] },
  { name: "contract-expired", title: "마지막 출근하고 고용센터", description: "계약 만료라 이직확인서 챙기기", expectedAny: ["unemployment"], allowedExtra: ["employment"] },
  { name: "certification-exam", title: "정처기 실기 원서 넣기", description: "응시료 결제", expectedAny: ["exam"] },
  { name: "studio-contract", title: "원룸 가계약금 보내는 날", description: "보증금과 월세 조건 확인", expectedAny: ["housing"] },
  { name: "move-broker-fee", title: "이삿짐이랑 복비 결제", description: "서울 새 자취방으로 이동", expectedAny: ["housing"] },
  { name: "earned-tax-credit", title: "홈택스 반기 신청", description: "근로장려금 안내문 확인", expectedAny: ["tax-credit"] },
  { name: "swimming-health", title: "새벽 자유수영 등록", description: "체력 회복하려고 주 3회 운동", expectedAny: ["sports"] },
  { name: "musical-booking", title: "뮤지컬 티켓팅", description: "주말 공연 예매", expectedAny: ["culture"] },
  { name: "bootcamp", title: "개발 캠프 상담", description: "직무 전환 교육과정 등록", expectedAny: ["education"] },
  { name: "tuition", title: "2학기 등록금 납부", description: "국가장학금 서류도 제출", expectedAny: ["scholarship"], allowedExtra: ["education"] },
  { name: "military-notice", title: "나라사랑카드 챙겨서 들어가는 날", description: "입영통지서에 적힌 훈련소 입소", expectedAny: ["military"] },
  { name: "health-check", title: "보건소에서 피검사", description: "1인가구 무료 건강검진 예약", expectedAny: ["health"], allowedExtra: ["family"] },
  { name: "counseling", title: "마음이 너무 무거워 상담 예약", description: "불안과 우울 때문에 심리상담", expectedAny: ["mental-health"] },
  { name: "startup-pitch", title: "사업 아이디어 발표", description: "예비창업자 데모데이 피칭", expectedAny: ["startup"] },
  { name: "savings-goal", title: "월급날 자동이체 설정", description: "청년 자산형성 통장으로 목돈 마련", expectedAny: ["assets"], allowedExtra: ["finance"] },
  { name: "marriage-registration", title: "둘이 구청 가는 날", description: "혼인신고서 제출하고 신혼 지원 확인", expectedAny: ["marriage"] },
  { name: "birth-registration", title: "아기 이름 올리기", description: "출생신고하고 주민번호 받기", expectedAny: ["childbirth"] },
  { name: "parental-leave", title: "인사팀에 휴직계 내기", description: "아이 돌보려고 육아휴직 신청", expectedAny: ["childcare"] },
  { name: "child-care", title: "어린이집 입소 상담", description: "보육료와 아이돌봄 서비스 문의", expectedAny: ["childcare"] },
  { name: "public-transit", title: "기후동행카드 충전", description: "버스 지하철 정기권", expectedAny: ["transport"] },
  { name: "finance-neutral", title: "은행 재무상담", description: "대출 권유가 아니라 금융교육 일정", expectedAny: ["finance", "education"] },
  { name: "job-fair", title: "채용박람회 다녀오기", description: "구직 상담과 이력서 첨삭", expectedAny: ["employment"] },
  { name: "field-practice", title: "학교 연계 현장실습 면담", description: "기업 직무체험 배정", expectedAny: ["work-experience"] },
  { name: "rent-renewal", title: "집주인이랑 재계약", description: "월세 계약 갱신", expectedAny: ["housing"] },
  { name: "smoking-clinic", title: "보건소 호흡 측정", description: "니코틴 끊는 상담 시작", expectedAny: ["health"] },
  { name: "family-dinner", title: "부모님 생신 저녁", description: "가족 식사 식당 예약", expectedAny: ["family", "general"], forbidden: ["childbirth", "childcare"] },
  { name: "not-quitting", title: "금연할 생각 없음", description: "친구와 잡담", expectedAny: ["general"], forbidden: ["health"] },
  { name: "not-moving", title: "이사 안 하기로 결정", description: "계약 일정 취소", expectedAny: ["general", "housing"], forbidden: [] },
  { name: "ordinary-birthday", title: "친구 생일파티", description: "케이크 픽업", expectedAny: ["general"], forbidden: ["childbirth", "marriage", "employment"] },
];
